# -*- coding: utf-8 -*-
"""Assignment-4  PLOTLY LIB

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17w1P-bJaK5D8F1TkGbTTtn9DfdpFa-Ex
"""

#Q1
#WHAT IS PLOTLY?
#A.PLOTLY is a platform to create data visualization.
#  You can use it with python, R, Julia, and a few other languages.
#  It’s incredibly user-friendly, has extensive documentation, and allows you to create very powerful graphs and charts with a few lines of code.
# It’ s biggest advantage is its ability to deploy the graphs to the web as web apps, by using Dash.

#Q2
#WHERE IS PLOTLY USED?
#A.PLOTLY is used to create your visualization since any complex plots only use three main concepts: data, layout, and figure objects. 
# We can also create a dashboard with PLOTLY Dash, a tool for displaying a collective set of PLOTLY charts.

#Q3
#Plot a Pie chart of Indian Car Companies market share in value%
import numpy as np 
 
import plotly 
 
import plotly.graph_objects as go

Car_Companies=['Maruthi Suzuki','Hyundai','Ford motors','Renault','Tata','Toyoto']

Market_Share=[50,17.4,1.9,3.3,7.15,3.25]

fig = go.Figure(data=[go.Pie(labels=Car_Companies,values=Market_Share)])
fig.show()

#Question 4
#plot a bar graph with covid-19 active cases(Max 10 states)

States=["Andaman and Nicobar","Andhra Pradesh","Nagaland","Rajasthan","Tamil Nadu"",Telengana","Delhi","Goa","kerala","Punjab"]
Cases=[7492,1920178,25898,953074,2516011,631218,1435030,168585,3053116,597469]
fig3 =go.Figure(data=go.Bar(x=States,y=Cases))
fig3.show()

#Question 5
#Plot a line chart with Indias active covid-19 case recovery(maximum 12 momths)

months=["12-aug-2020","8-sep-2020","3-oct-2020"",12-nov-2020","7-dec-2020","2-jan-2021","11-feb-2021","6-march-2021","2-april-2021","23-may-2021","18-june-2021","3-july-2021"]
recovered=[24752 , 5650907 , 272455 ,26818, 2499784, 28798 ,242438, 33764 , 1945260,168068,418285 , 1627390]
fig2 =go.Figure(data=go.Scatter(x=months,y=recovered))
fig2.show()
